Property1
Scope:BetweenLandR
CPL:EventualE(l1,l2,l3)
CPR:EventualE(r1,r2,r3)
Pattern:Response
CPP:ParallelC(p1,p2,p3)
CPQ:AtLeastOneC(q1,q2,q3)
Property2
Scope:BetweenLandR
CPL:AtLeastOneE(l1,l2,l3)
CPR:AtLeastOneC(r1,r2,r3)
Pattern:Response
CPP:EventualE(p1,p2,p3)
CPQ:AtLeastOneE(q1,q2,q3)
Property3
Scope:BetweenLandR
CPL:AtLeastOneE(l1,l2,l3)
CPR:AtLeastOneE(r1,r2,r3)
Pattern:Response
CPP:EventualC(p1,p2,p3)
CPQ:AtLeastOneC(q1,q2,q3)
Property4
Scope:BetweenLandR
CPL:ParallelC(l1,l2,l3)
CPR:ConsecutiveC(r1,r2,r3)
Pattern:Response
CPP:EventualE(p1,p2,p3)
CPQ:ParallelE(q1,q2,q3)
Property5
Scope:BetweenLandR
CPL:ParallelC(l1,l2,l3)
CPR:ConsecutiveE(r1,r2,r3)
Pattern:Response
CPP:EventualC(p1,p2,p3)
CPQ:ParallelC(q1,q2,q3)
Property6
Scope:BetweenLandR
CPL:EventualE(l1,l2,l3)
CPR:ParallelC(r1,r2,r3)
Pattern:Response
CPP:ConsecutiveE(p1,p2,p3)
CPQ:AtLeastOneE(q1,q2,q3)
Property7
Scope:BetweenLandR
CPL:EventualE(l1,l2,l3)
CPR:ParallelE(p1,p2,p3)
Pattern:Response
CPP:ConsecutiveC(p1,p2,p3)
CPQ:ParallelC(q1,q2,q3)
Property8
Scope:BetweenLandR
CPL:ParallelC(l1,l2,l3)
CPR:EventualC(r1,r2,r3)
Pattern:Response
CPP:ParallelC(p1,p2,p3)
CPQ:AtLeastOneC(q1,q2,q3)
Property9
Scope:BetweenLandR
CPL:ConsecutiveE(l1,l2,l3)
CPR:ParallelE(p1,p2,p3)
Pattern:Response
CPP:AtLeastOneC(p1,p2,p3)
CPQ:EventualC(q1,q2,q3)
Property10
Scope:BetweenLandR
CPL:ParallelC(p1,p2,p3)
CPR:EventualE(r1,r2,r3)
Pattern:Response
CPP:ParallelE(p1,p2,p3)
CPQ:AtLeastOneE(q1,q2,q3)
Property11
Scope:BetweenLandR
CPL:ParallelE(l1,l2,l3)
CPR:ParallelE(r1,r2,r3)
Pattern:Response
CPP:EventualC(p1,p2,p3)
CPQ:AtLeastOneE(q1,q2,q3)
Property12
Scope:BetweenLandR
CPL:ParallelE(l1,l2,l3)
CPR:AtLeastOneC(r1,r2,r3)
Pattern:Response
CPP:EventualE(p1,p2,p3)
CPQ:AtLeastOneC(q1,q2,q3)
Property13
Scope:BetweenLandR
CPL:ConsecutiveC(l1,l2,l3)
CPR:AtLeastOneE(r1,r2,r3)
Pattern:Response
CPP:AtLeastOneE(p1,p2,p3)
CPQ:AtLeastOneC(q1,q2,q3)
Property14
Scope:BetweenLandR
CPL:EventualC(l1,l2,l3)
CPR:AtLeastOneC(r1,r2,r3)
Pattern:Response
CPP:AtLeastOneC(p1,p2,p3)
CPQ:AtLeastOneC(q1,q2,q3)
Property15
Scope:BetweenLandR
CPL:EventualC(l1,l2,l3)
CPR:AtLeastOneC(r1,r2,r3)
Pattern:Response
CPP:AtLeastOneE(p1,p2,p3)
CPQ:AtLeastOneC(q1,q2,q3)